name: Minha Pipeline

on:
  push:
    branches: 
      - '**'

jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run prettier
      - run: npm run build

